export const featuredGames = [
  {
    key: "bingo",
    title: "Play Bingo",
    image: "/images/bingo.png",
    enabled: true,
    isNew: false,
    featured: true,
    to: "/bingo-rooms",
  },
  {
    key: "ludo",
    title: "Play Ludo 1V1",
    image: "/images/ludo.png",
    enabled: true,
    isNew: false,
    featured: true,
    to: "/ludo/2",
  },
  {
    key: "crazy_bingo",
    title: "Crazy Bingo",
    image: "/images/crazy.png",
    enabled: false,
    isNew: true,
    featured: false,
  },
  {
    key: "xo",
    title: "XO",
    image: "/images/xo.png",
    enabled: false,
    isNew: true,
    featured: false,
  },
  {
    key: "ludo_4p",
    title: "Ludo 4 Player",
    image: "/images/ludoicon.png",
    enabled: true,
    isNew: false,
    featured: false,
    to: "/ludo/4",
  },

  {
    key: "keskesh",
    title: "Keshkesh",
    image: "/images/keskesh.png",
    enabled: false,
    isNew: false,
    featured: false,
  },
  {
    key: "habesha_pool",
    title: "Habesha Pool",
    image: "/images/pool.png",
    enabled: false,
    isNew: false,
    featured: false,
  },
  {
    key: "connect4",
    title: "Connect 4",
    image: "/images/connect4.png",
    enabled: false,
    isNew: false,
    featured: false,
  },
  {
    key: "dama",
    title: "Dama",
    image: "/images/dama.png",
    enabled: false,
    isNew: false,
    featured: false,
  },
  {
    key: "conquer",
    title: "Conquer",
    image: "/images/conquer.png",
    enabled: false,
    isNew: false,
    featured: false,
  },
  {
    key: "pool",
    title: "Pool",
    image: "/images/pool-1.png",
    enabled: false,
    isNew: false,
    featured: false,
  },
  {
    key: "uno",
    title: "Uno",
    image: "/images/uno.png",
    enabled: false,
    isNew: false,
    featured: false,
  },
  {
    key: "penalty",
    title: "Penalty",
    image: "/images/penalty.png",
    enabled: false,
    isNew: false,
    featured: false,
  },
  {
    key: "gin_rummy",
    title: "Gin Rummy",
    image: "/images/gin_rummy.png",
    enabled: false,
    isNew: false,
    featured: false,
  },
  {
    key: "memory_game",
    title: "Memory Game",
    image: "/images/memory.png",
    enabled: false,
    isNew: false,
    featured: false,
  },
  {
    key: "spin",
    title: "Spin Game",
    image: "/images/spin.png",
    enabled: false,
    isNew: true,
    featured: false,
    to: "/spin-rooms",
  },
  {
    key: "material_lottery",
    title: "Material Lottery",
    image: "/images/money.png",
    enabled: false,
    isNew: true,
    featured: false,
    to: "/material-lottery-rooms",
  },
  {
    key: "bulls_cows",
    title: "Bulls & Cows",
    image: "/images/bulls.png",
    enabled: false,
    isNew: false,
    featured: false,
  },
  {
    key: "latlat",
    title: "Latlat",
    image: "/images/latlat.png",
    enabled: false,
    isNew: false,
    featured: false,
  },
];